### ISSUE TITLE
RDFS interpretation for NIEM XML?

### ISSUE THREAD

**Issue by iamdrscott** [NIEM/NIEM-JSON-Spec#10]
rule 4-4:  We don't have this RDFS-interpretation rule for NIEM XML.  Do we need it in the NDR?  Is it necessarily satisfied in XML?

**Comment by webb** [comment]
This should go in NDR section 5: That the meaning of an XML instance is the interpretation of the RDF for an instance against the RDF (RDFS) for the schema.

**Comment by webb** [comment]
Issue moved to NDR: https://github.com/NIEM/NIEM-NDR/issues/79
