### ISSUE TITLE
Add Audience section

### ISSUE THREAD

**Issue by cabralje** [NIEM/NIEM-JSON-Spec#12]
1.1 Audience
The primary target of this guidance is the tool developer implementing tools to generate JSON instances (messages) that conform with the NIEM.

Developers looking to develop NIEM message specifications (IEPDs) including JSON representations, should refer instead to the [Non-Normative Guidance in Using NIEM with JSON](http://niem.github.io/json/reference/guidance/) document.

**Comment by webb** [comment]
Generalize to tools working with NIEM JSON. Distinguish between tools developers & message description developers.
Point them to the best landing page for NIEM JSON.
