### ISSUE TITLE
Notes on the spec

### ISSUE THREAD

**Issue by mark-aamva** [NIEM/NIEM-JSON-Spec#16]
I would like to have more time to look at the spec, but I keep getting dragged on to other tasks. I used mark-up in the document to add some notes.

[NIEM JSON Specification.docx](https://github.com/NIEM/NIEM-JSON-Spec/files/5197309/NIEM.JSON.Specification.docx)

**Comment by webb** [comment]
I converted comments in the doc into issues. 
[NIEM.JSON.Specification+responses.docx](https://github.com/NIEM/NIEM-JSON-Spec/files/5431926/NIEM.JSON.Specification%2Bresponses.docx)
