### ISSUE TITLE
Consider attaching a context to an instance as part of a data normalization stage

### ISSUE THREAD

**Issue by webb** [NIEM/NIEM-JSON-Spec#23]
We currently have literal-to-object conversion as a step for normalizing a JSON file to be conformant JSON-LD.

We don't want to require attaching contexts to runtime data, in most cases.

Consider expanding the literal-to-object conversion to be a stage for JSON-LD normalization, which would include literal-to-object conversion, as well attaching a context as provided my a message specification.

This may involve a new conformance target, for a de-normalized JSON instance. 

See <https://github.com/NIEM/NIEM-JSON-Spec/wiki/NIEM-JSON-normalization> for an explanation.

**Comment by TomCarlson-NTAC** [comment]
Added normalization section with context.
