### ISSUE TITLE
External content conformance

### ISSUE THREAD

**Issue by iamdrscott** [NIEM/NIEM-JSON-Spec#9]
Instead of presuming all external content is conforming, perhaps we could have a rule similar to XML Schema's strict/lax/skip conformance for wildcards.

+ strict: The JSON is NIEM-conforming if and only if there is a separate conformance test for all external content AND all external content satisfies the corresponding test

+ lax: The JSON is NIEM-conforming UNLESS there is a separate conformance test for some external content AND external content which fails that test

+ skip:  Forget it, Jake, it's Chinatown

**Comment by webb** [comment]
§4.2 says the content of an external adapter is outside the scope of conformance with respect to this specification. 
XML is XML and JSON is JSON, and if there's an RDF interpretation or JSON projection of an XML blob, that's just not something we can handle here. We should make sure the NDR says what we want it to say: An instance of a NIEM XML external adapter type should entail RDF that makes the external content a blank node.

**Comment by webb** [comment]
Text to fix from the JSON spec, section 4.2: 

> NIEM does not provide external content with an RDF mapping. As such, external content is outside the scope of evaluation of conformance of JSON documents.

This is not quite right; the internals of external content is outside the scope 

NDR 5.6.3.4. Element as a simple property of an object or association : 

> $object is a node identifier for the object held by $element.

NDR 5.6.3.2. Element instance : 

> $object rdf:type $type .
>
> Where:
>
> $object is a node identifier for the object held by $element.

5.4. Unique identification of data objects : 

> if the above attributes do not appear on an object, then an object may be treated as a blank node, and assigned a blank node identifier.
